name: CI - Run all tests

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-all-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run all tests (multi-module)
        run: mvn -B test

      - name: Upload all surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-surefire-reports
          path: '**/target/surefire-reports'
