name: Smoke Tests

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: smoke-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Run smoke tests
        run: |
          if [ -f ./mvnw ]; then
            chmod +x ./mvnw
            ./mvnw -B -f smoke-tests test
          else
            mvn -B -f smoke-tests test
          fi
      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-tests-reports
          path: smoke-tests/target/surefire-reports
